dist: trusty
addons:
    apt:
        packages:
            - xvfb

    install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

matrix:
    fast_finish: true

branches:
    only:
        - master

language: node_js
node_js:
    - '8.11.3'

cache:
    yarn: true
    directories:
        - node_modules
        - $HOME/.electron
        - .eslintcache
        - $HOME/.cache/electron-builder


before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
    - export PATH=$HOME/.yarn/bin:$PATH

install:
    - yarn install --force

script:
    - yarn test
