sudo: required
dist: trusty
matrix:
    fast_finish: true

branches:
    only:
        - develop
        - master

language: node_js
node_js:
    - '8.11.3'

cache:
    yarn: true
    directories:
        - node_modules
        - $HOME/.electron
        - .eslintcache
        - $HOME/.cache/electron-builder


before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
    - export PATH=$HOME/.yarn/bin:$PATH
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

install:
    - yarn install

script:
    - yarn test
